const mongoose=require('mongoose');

const customerSchema=new mongoose.Schema({

    referralCode:{
        type:String
    },
    username:{
        type:String,
        unique:true,
        index:true,
        sparse:true
    },
    customerStatusId:{
        type:Number,
        default:0
    },
    walletBalance:{
        type:Number,
        default:0
    },
    customerId:{
        type:String,
        unique:true,
        sparse:true,
        index:true

    },
    userState:{
        type:String,
        default:"Normal"
    },
    role:{
        type:String,
        default:"customer"
    },
    nickname:{
        type:String
    },
    email:{
        type:String,
        unique:true,
        index:true,
        sparse:true
    },
    password:{
        type:String
    },
    userBankName:{
        type:String
    },
    userBankAccountNumber:{
        type:Number,
        unique:true,
        index:true,
        sparse:true
    },
    userBankAccountHolderName:{
        type:String
    },
    mobileNumber:{
        type:Number,
        unique:true,
        index:true,
        sparse:true
    },
    countryCode:{
        type:Number
    },
    mobileOtp:{
        type:String
    },
    emailOtp:{
        type:String
    },
    emailOtpExpiryTime:{
        type:Date
    },
    mobileOtpExpiryTime:{
        type:Date
    },
    isAccountBlocked:{
        type:Boolean,
        default:false
    },
    isEmailVerified:{
        type:Boolean,
        default:false
    },
    isMobileNumberVerified:{
        type:Boolean,
        default:false
    },
    isBankDetailsUpdated:{
        type:Boolean,
        default:false
    },
    token:{
        type:String
    },
    lastLoginTime:{
        type:Date
    },
    isLoggedIn:{
        type:Boolean,
        default:false
    },
    totalDepositAmount:{
        type:Number,
        default:0
    },
    totalWithdrawlAmount:{
        type:Number,
        default:0
    },
    totalRevenueAmount:{
        type:Number,
        default:0
    }
},{timestamps:true,versionKey:false});

const Customer=new mongoose.model("customers",customerSchema);

module.exports=Customer;